### ISSUE TITLE
upload artifacts is actually taking over a hour

### ISSUE THREAD

**Issue by player-k12** [eaglercrack-archive/eaglercrack-archive.github.io#9]
To improve speed, could we update the GitHub actions upload artifact to v4?

**Comment by Proofr** [comment]
idk what that is

**Comment by player-k12** [comment]
google it

**Comment by radmanplays** [comment]
> idk what that is

when you host a website in github pages theres a section in the settings tab called "pages". click on that and then change "Deploy from a branch" to "github actions" and click on the blue text that says "create your own" and commit the file that it wants you to create

**Comment by radmanplays** [comment]
it makes deploying to github pages 10 times faster and lets you customize it

**Comment by Proofr** [comment]
> > idk what that is
> 
> when you host a website in github pages theres a section in the settings tab called "pages". click on that and then change "Deploy from a branch" to "github actions" and click on the blue text that says "create your own" and commit the file that it wants you to create

added that

**Comment by player-k12** [comment]
Fixed issue
